---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nginx-dev

namespace: nginx-dev

resources:
  - ../../base
  - namespace.yaml

patches:
  - path: patches/replica-patch.yaml
    target:
      kind: Deployment
      name: nginx

labels:
  - pairs:
      environment: dev

namePrefix: dev-

commonAnnotations:
  environment: development
  maintainer: devops-team
