---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-sieczak-cloud-cert
  namespace: istio-ingress
spec:
  secretName: argo-sieczak-cloud-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - argo.sieczak.cloud
