---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  project: default
  source:
    chart: keycloak
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 24.7.7
    helm:
      values: |
        auth:
          adminUser: admin
          existingSecret: "keycloak-app-secret"
          passwordSecretKey: "admin-password"
        proxyHeaders: "xforwarded"
        postgresql:
          enabled: true
          auth:
            username: bn_keycloak
            database: bitnami_keycloak
            existingSecret: "keycloak-app-secret"
            secretKeys:
              userPasswordKey: postgres-password
          architecture: standalone
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
