---
extraEnvVars:
  - name: KC_PROXY
    value: edge
  - name: KC_HOSTNAME
    value: keycloak.sieczak.cloud
  - name: KC_HOSTNAME_STRICT
    value: "true"
  - name: KC_HOSTNAME_STRICT_HTTPS
    value: "true"
