---
extraEnvVars:
  - name: KC_PROXY_HEADERS
    value: xforwarded

postgresql:
  enabled: true
  auth:
    postgresPassword: ""
    username: bn_keycloak
    password: "random-pass"
    database: bitnami_keycloak
    # existingSecret: "keycloak-pg-pass"
    # secretKeys:
    #   userPasswordKey: postgres-password
  architecture: standalone
