---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: keycloak-gateway
  namespace: keycloak
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - keycloak.sieczak.cloud
        - keycloak.keycloak.svc.cluster.local
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - keycloak.sieczak.cloud
        - keycloak.keycloak.svc.cluster.local
      tls:
        mode: SIMPLE
        credentialName: keycloak-sieczak-cloud-tls
