---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-sieczak-cloud-cert
  namespace: istio-ingress
spec:
  secretName: keycloak-sieczak-cloud-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - keycloak.sieczak.cloud
