---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: keycloak-secret
  namespace: keycloak
spec:
  vaultAuthRef: vault-auth
  mount: kv
  type: kv-v2
  path: keycloak
  destination:
    create: true
    name: keycloak-app-secret
  refreshAfter: 1h
